services:
  postgres:
    container_name: postgres_users_instant_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "51756:51756"
      - "55403:55403"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: no

networks:
  postgres:
    driver: bridge

volumes:
  postgres: