global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323'] # Docker metrics

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100'] # Node exporter

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:51756'] # Ваш auth-service

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8081'] # Ваш chat-service

  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kafka:9997'] # Kafka JMX exporter

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187'] # Postgres exporter

rule_files:
  - '/etc/prometheus/alert.rules.yml'